name: noitu
description: Chơi nối từ

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  rflutter_alert: ^1.0.3
  material_design_icons_flutter: ^3.2.4495
  sqflite: ^1.3.0
  path: ^1.6.4
  flutter_spinkit: ^4.1.2
  date_format: ^1.0.8
  screenshot: ^0.1.1
  esys_flutter_share: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  image_path_android: "assets/ic_launcher.png"
  image_path_ios: "assets/ic_launcher_ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # flutter pub pub run flutter_launcher_icons:main
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/words.db
  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf